### ISSUE TITLE
why another cli for aria2?

### ISSUE THREAD

**Issue by shangxinbo** [sonnyp/aria2.js#28]
I guess the aria2 is a cli utility original.Why this lib gives another cli?  why take the trouble to do that?

**Comment by sonnyp** [comment]
`aria2.js` is a JavaScript library for aria2 RPC/ remote interface. The CLI shipped with aria2.js is mostly for testing and for fun, plus as far I know aria2 CLI doesn't do remote control of an aria2 daemon.
