### ISSUE TITLE
How can I track the progress of the download?

### ISSUE THREAD

**Issue by shangxinbo** [sonnyp/aria2.js#30]
I come to know that aria2 can print a readout to the console to show the progress of the downloads. look like this:
```
[#2089b0 400.0KiB/33.2MiB(1%) CN:1 DL:115.7KiB ETA:4m51s]
```
How can I track this progress info?May I polling？

**Comment by sonnyp** [comment]
yes polling is your best option

**Comment by shangxinbo** [comment]
oh my god!
