### ISSUE TITLE
Uncaught (in promise) TypeError: this is undefined

### ISSUE THREAD

**Issue by baptistecdr** [sonnyp/aria2.js#54]
Hello,
Thank you for your work, but since v4.1.1, it doesn't work properly. I get this error :

<img width="879" alt="Capture d’écran 2020-12-29 à 11 33 49" src="https://user-images.githubusercontent.com/11665396/103277845-2ea94a00-49ca-11eb-8513-cab2899fdfd6.png">

With this simple code for example :
```js
this.aria2 = new Aria2({
      host: 'localhost',
      port: 6800,
      secure: false,
      secret: 'Test',
      path: '/jsonrpc'
    });
    const res = await this.aria2.call('getGlobalStat', [], {});
    console.log(res);
```

It was working fine with the 4.1.0 :
<img width="1082" alt="Capture d’écran 2020-12-29 à 11 34 53" src="https://user-images.githubusercontent.com/11665396/103277894-57c9da80-49ca-11eb-9b81-aa902948a239.png">

Best regards,
baptistecdr

**Comment by sonnyp** [comment]
fixed in 4.1.2
