### ISSUE TITLE
FetchError: ECONNREFUSED

### ISSUE THREAD

**Issue by twio142** [sonnyp/aria2.js#66]
I keep getting this error: `FetchError: request to http://localhost:6800/jsonrpc failed, reason: connect ECONNREFUSED ::1:6800`

Aria2 RPC works elsewhere with no problem, and I’m pretty sure I got the RPC path and secret right. What could be the reason?

**Comment by sonnyp** [comment]
I don't know but it's not an issue with aria2.js

**Comment by twio142** [comment]
I actually solved that problem. Just needed to change `host` in default options to '127.0.0.1', because I'm not using an IPv6 address.
